const {test}=require('node:test');const assert=require('node:assert/strict');
const {normalizeDetails}=require('../services/product-details');const {materialPayload,validateReferences,rejectPersonalReferences,hydrateProducts}=require('../services/merchant-materials');
const fixture=require('./fixtures/artwork-product.json');
const m={id:12,merchant_user_id:3,brand:'禾居',kind:'fabric',series:'A',name:'米白',code:'A01',status:'active',description:'',image_urls:[],revision:1};
const dbFor=(rows)=>({query:async(sql,args)=>[rows.filter(r=>r.merchant_user_id===args[0]&&args.slice(1).includes(r.id))]});
function details(){const d=structuredClone(fixture);d.material_groups=[{part:'画面',material_ids:[12]}];d.configurations[0].parts=[{part:'画面',material_id:12,material_revision:null}];d.configurations[0].material_options=[{part:'画面',material_ids:[12]}];return normalizeDetails(d,'artwork');}
test('material input is bounded and supplier states explicit',()=>{assert.equal(materialPayload(m).status,'active');for(const body of [{...m,status:'deleted'},{...m,code:''},{...m,image_urls:['javascript:alert(1)']},{...m,kind:'invalid'}])assert.throws(()=>materialPayload(body));});
test('merchant library is owner-scoped; personal catalogs cannot use library references',async()=>{assert.throws(()=>rejectPersonalReferences(details()));await assert.rejects(validateReferences(dbFor([m]),details(),8),/本商家/);const d=JSON.parse(await validateReferences(dbFor([m]),details(),3));assert.equal(d.configurations[0].parts[0].color,'米白');assert.equal(d.configurations[0].parts[0].material_revision,1);const invalid=details();invalid.material_groups=[];await assert.rejects(validateReferences(dbFor([m]),invalid,3),/可用范围/);});
test('stopped material keeps old references but cannot be selected into new configs or products',async()=>{const old=JSON.parse(await validateReferences(dbFor([m]),details(),3));const stopped={...m,status:'discontinued',revision:2};await assert.rejects(validateReferences(dbFor([stopped]),old,3),/新增选用/);const retained=JSON.parse(await validateReferences(dbFor([stopped]),old,3,old));assert.equal(retained.configurations[0].parts[0].material_revision,1);const copy=structuredClone(old);copy.configurations[0].id='new-config';await assert.rejects(validateReferences(dbFor([stopped]),copy,3,old),/新增选用/);const [live]=await hydrateProducts(dbFor([stopped]),[{merchant_user_id:3,product_details:old}]);assert.equal(live.product_details.material_warnings[0].status,'discontinued');assert.equal(live.product_details.configurations[0].parts[0].material_changed,true);assert.equal(live.product_details.configurations[0].parts[0].color,'米白');});
test('live read exposes only referenced materials belonging to the product owner',async()=>{const [p]=await hydrateProducts(dbFor([m,{...m,id:13,name:'隐藏色号'}]),[{merchant_user_id:3,product_details:details()}]);assert.equal(p.product_details.material_groups[0].materials.length,1);assert.equal(JSON.stringify(p).includes('隐藏色号'),false);const [foreign]=await hydrateProducts(dbFor([m]),[{merchant_user_id:8,product_details:details()}]);assert.equal(foreign.product_details.material_groups[0].materials[0].status,'unavailable');assert.equal(JSON.stringify(foreign.product_details.configurations[0].parts[0].live_material).includes('米白'),false);});
