ALTER TABLE merchant_profiles
  ADD COLUMN IF NOT EXISTS shop_name VARCHAR(120) DEFAULT NULL AFTER user_id,
  ADD COLUMN IF NOT EXISTS logo_url VARCHAR(500) DEFAULT NULL AFTER shop_name,
  ADD COLUMN IF NOT EXISTS cover_url VARCHAR(500) DEFAULT NULL AFTER logo_url,
  ADD COLUMN IF NOT EXISTS address VARCHAR(255) DEFAULT NULL AFTER service_area,
  ADD COLUMN IF NOT EXISTS contact_phone VARCHAR(40) DEFAULT NULL AFTER address,
  ADD COLUMN IF NOT EXISTS business_hours VARCHAR(120) DEFAULT NULL AFTER contact_phone,
  ADD COLUMN IF NOT EXISTS category_group VARCHAR(20) DEFAULT NULL AFTER business_hours,
  ADD COLUMN IF NOT EXISTS after_sales_promise TEXT DEFAULT NULL AFTER brand_intro,
  ADD COLUMN IF NOT EXISTS license_url VARCHAR(500) DEFAULT NULL AFTER after_sales_promise,
  ADD COLUMN IF NOT EXISTS authorization_url VARCHAR(500) DEFAULT NULL AFTER license_url;
