CREATE TABLE IF NOT EXISTS desktop_release_upload_sessions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_token CHAR(36) NOT NULL,
  upload_id VARCHAR(255) NOT NULL,
  storage_key VARCHAR(700) NOT NULL,
  platform ENUM('windows', 'macos') NOT NULL,
  version_name VARCHAR(64) NOT NULL,
  build_number INT UNSIGNED NOT NULL,
  original_name VARCHAR(255) NOT NULL,
  file_size BIGINT UNSIGNED NOT NULL,
  content_type VARCHAR(150) NOT NULL DEFAULT 'application/octet-stream',
  release_notes TEXT NOT NULL,
  update_mode ENUM('optional', 'required') NOT NULL DEFAULT 'optional',
  part_size INT UNSIGNED NOT NULL,
  part_count INT UNSIGNED NOT NULL,
  status ENUM('pending', 'completed', 'aborted', 'expired') NOT NULL DEFAULT 'pending',
  created_by VARCHAR(64) NOT NULL DEFAULT 'admin',
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_desktop_release_upload_session_token (session_token),
  KEY idx_desktop_release_upload_status_expiry (status, expires_at),
  KEY idx_desktop_release_upload_storage_key (storage_key(191))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
